"""Adiciona usuario_id na tabela Memoria

Revision ID: 0e78a0453aaa
Revises: 10b0adfea602
Create Date: 2025-04-19 16:55:12.983570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e78a0453aaa'
down_revision = '10b0adfea602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('imagem',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
